// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: grpc/proto/ailocalcli.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest_Mode int32

const (
	GetStatsRequest_DAILY   GetStatsRequest_Mode = 0
	GetStatsRequest_MONTHLY GetStatsRequest_Mode = 1
	GetStatsRequest_VERBOSE GetStatsRequest_Mode = 2
)

// Enum value maps for GetStatsRequest_Mode.
var (
	GetStatsRequest_Mode_name = map[int32]string{
		0: "DAILY",
		1: "MONTHLY",
		2: "VERBOSE",
	}
	GetStatsRequest_Mode_value = map[string]int32{
		"DAILY":   0,
		"MONTHLY": 1,
		"VERBOSE": 2,
	}
)

func (x GetStatsRequest_Mode) Enum() *GetStatsRequest_Mode {
	p := new(GetStatsRequest_Mode)
	*p = x
	return p
}

func (x GetStatsRequest_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetStatsRequest_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_proto_ailocalcli_proto_enumTypes[0].Descriptor()
}

func (GetStatsRequest_Mode) Type() protoreflect.EnumType {
	return &file_grpc_proto_ailocalcli_proto_enumTypes[0]
}

func (x GetStatsRequest_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetStatsRequest_Mode.Descriptor instead.
func (GetStatsRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{13, 0}
}

// Routes
type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{0}
}

type RouteInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Quota         string                 `protobuf:"bytes,2,opt,name=quota,proto3" json:"quota,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteInfo) Reset() {
	*x = RouteInfo{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteInfo) ProtoMessage() {}

func (x *RouteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteInfo.ProtoReflect.Descriptor instead.
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{1}
}

func (x *RouteInfo) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RouteInfo) GetQuota() string {
	if x != nil {
		return x.Quota
	}
	return ""
}

func (x *RouteInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteInfo           `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoutesResponse) GetRoutes() []*RouteInfo {
	if x != nil {
		return x.Routes
	}
	return nil
}

// Quotas
type ListQuotasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotasRequest) Reset() {
	*x = ListQuotasRequest{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotasRequest) ProtoMessage() {}

func (x *ListQuotasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotasRequest.ProtoReflect.Descriptor instead.
func (*ListQuotasRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{3}
}

type QuotaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Daily         int64                  `protobuf:"varint,2,opt,name=daily,proto3" json:"daily,omitempty"`
	Monthly       int64                  `protobuf:"varint,3,opt,name=monthly,proto3" json:"monthly,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // APPLIED or IDLE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaInfo) Reset() {
	*x = QuotaInfo{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfo) ProtoMessage() {}

func (x *QuotaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfo.ProtoReflect.Descriptor instead.
func (*QuotaInfo) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{4}
}

func (x *QuotaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuotaInfo) GetDaily() int64 {
	if x != nil {
		return x.Daily
	}
	return 0
}

func (x *QuotaInfo) GetMonthly() int64 {
	if x != nil {
		return x.Monthly
	}
	return 0
}

func (x *QuotaInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *QuotaInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListQuotasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotas        []*QuotaInfo           `protobuf:"bytes,1,rep,name=quotas,proto3" json:"quotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotasResponse) Reset() {
	*x = ListQuotasResponse{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotasResponse) ProtoMessage() {}

func (x *ListQuotasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotasResponse.ProtoReflect.Descriptor instead.
func (*ListQuotasResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{5}
}

func (x *ListQuotasResponse) GetQuotas() []*QuotaInfo {
	if x != nil {
		return x.Quotas
	}
	return nil
}

// Keys
type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{6}
}

type KeyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	RealKey       string                 `protobuf:"bytes,4,opt,name=real_key,json=realKey,proto3" json:"real_key,omitempty"`
	InternalKey   string                 `protobuf:"bytes,5,opt,name=internal_key,json=internalKey,proto3" json:"internal_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyInfo) Reset() {
	*x = KeyInfo{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyInfo) ProtoMessage() {}

func (x *KeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyInfo.ProtoReflect.Descriptor instead.
func (*KeyInfo) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{7}
}

func (x *KeyInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *KeyInfo) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *KeyInfo) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *KeyInfo) GetRealKey() string {
	if x != nil {
		return x.RealKey
	}
	return ""
}

func (x *KeyInfo) GetInternalKey() string {
	if x != nil {
		return x.InternalKey
	}
	return ""
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyInfo             `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{8}
}

func (x *ListKeysResponse) GetKeys() []*KeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

type AddKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         string                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	RealKey       string                 `protobuf:"bytes,2,opt,name=real_key,json=realKey,proto3" json:"real_key,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyRequest) Reset() {
	*x = AddKeyRequest{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyRequest) ProtoMessage() {}

func (x *AddKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyRequest.ProtoReflect.Descriptor instead.
func (*AddKeyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{9}
}

func (x *AddKeyRequest) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *AddKeyRequest) GetRealKey() string {
	if x != nil {
		return x.RealKey
	}
	return ""
}

func (x *AddKeyRequest) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type AddKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InternalKey   string                 `protobuf:"bytes,1,opt,name=internal_key,json=internalKey,proto3" json:"internal_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeyResponse) Reset() {
	*x = AddKeyResponse{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeyResponse) ProtoMessage() {}

func (x *AddKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeyResponse.ProtoReflect.Descriptor instead.
func (*AddKeyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{10}
}

func (x *AddKeyResponse) GetInternalKey() string {
	if x != nil {
		return x.InternalKey
	}
	return ""
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteKeyRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  GetStatsRequest_Mode   `protobuf:"varint,1,opt,name=mode,proto3,enum=grpc.GetStatsRequest_Mode" json:"mode,omitempty"`
	// Filters (Optional depending on mode)
	StartDate     string `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate       string `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD
	Year          int32  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`                           // YYYY
	MaxCount      int32  `protobuf:"varint,5,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`   // Limit for verbose mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsRequest) GetMode() GetStatsRequest_Mode {
	if x != nil {
		return x.Mode
	}
	return GetStatsRequest_DAILY
}

func (x *GetStatsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetStatsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetStatsRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GetStatsRequest) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

type DailyStatRow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Date             string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	RoutePath        string                 `protobuf:"bytes,2,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	LocalKey         string                 `protobuf:"bytes,3,opt,name=local_key,json=localKey,proto3" json:"local_key,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	LastActivity     string                 `protobuf:"bytes,8,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"` // RFC3339 or "YYYY-MM-DD HH:MM:SS"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DailyStatRow) Reset() {
	*x = DailyStatRow{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStatRow) ProtoMessage() {}

func (x *DailyStatRow) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStatRow.ProtoReflect.Descriptor instead.
func (*DailyStatRow) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{14}
}

func (x *DailyStatRow) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStatRow) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *DailyStatRow) GetLocalKey() string {
	if x != nil {
		return x.LocalKey
	}
	return ""
}

func (x *DailyStatRow) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *DailyStatRow) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *DailyStatRow) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *DailyStatRow) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *DailyStatRow) GetLastActivity() string {
	if x != nil {
		return x.LastActivity
	}
	return ""
}

type MonthlyStatRow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Month            string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // YYYY-MM
	RoutePath        string                 `protobuf:"bytes,2,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	LocalKey         string                 `protobuf:"bytes,3,opt,name=local_key,json=localKey,proto3" json:"local_key,omitempty"`
	TotalRequests    int64                  `protobuf:"varint,4,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MonthlyStatRow) Reset() {
	*x = MonthlyStatRow{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyStatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyStatRow) ProtoMessage() {}

func (x *MonthlyStatRow) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyStatRow.ProtoReflect.Descriptor instead.
func (*MonthlyStatRow) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{15}
}

func (x *MonthlyStatRow) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyStatRow) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *MonthlyStatRow) GetLocalKey() string {
	if x != nil {
		return x.LocalKey
	}
	return ""
}

func (x *MonthlyStatRow) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *MonthlyStatRow) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *MonthlyStatRow) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *MonthlyStatRow) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type VerboseStatRow struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timestamp        string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id               int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	LocalKey         string                 `protobuf:"bytes,3,opt,name=local_key,json=localKey,proto3" json:"local_key,omitempty"`
	RoutePath        string                 `protobuf:"bytes,4,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	PromptTokens     int64                  `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	ClientIp         string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	CompletionTokens int64                  `protobuf:"varint,7,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int64                  `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerboseStatRow) Reset() {
	*x = VerboseStatRow{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerboseStatRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerboseStatRow) ProtoMessage() {}

func (x *VerboseStatRow) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerboseStatRow.ProtoReflect.Descriptor instead.
func (*VerboseStatRow) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{16}
}

func (x *VerboseStatRow) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *VerboseStatRow) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VerboseStatRow) GetLocalKey() string {
	if x != nil {
		return x.LocalKey
	}
	return ""
}

func (x *VerboseStatRow) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *VerboseStatRow) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *VerboseStatRow) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *VerboseStatRow) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *VerboseStatRow) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DailyRows     []*DailyStatRow        `protobuf:"bytes,1,rep,name=daily_rows,json=dailyRows,proto3" json:"daily_rows,omitempty"`
	MonthlyRows   []*MonthlyStatRow      `protobuf:"bytes,2,rep,name=monthly_rows,json=monthlyRows,proto3" json:"monthly_rows,omitempty"`
	VerboseRows   []*VerboseStatRow      `protobuf:"bytes,3,rep,name=verbose_rows,json=verboseRows,proto3" json:"verbose_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_ailocalcli_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_ailocalcli_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatsResponse) GetDailyRows() []*DailyStatRow {
	if x != nil {
		return x.DailyRows
	}
	return nil
}

func (x *GetStatsResponse) GetMonthlyRows() []*MonthlyStatRow {
	if x != nil {
		return x.MonthlyRows
	}
	return nil
}

func (x *GetStatsResponse) GetVerboseRows() []*VerboseStatRow {
	if x != nil {
		return x.VerboseRows
	}
	return nil
}

var File_grpc_proto_ailocalcli_proto protoreflect.FileDescriptor

const file_grpc_proto_ailocalcli_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpc/proto/ailocalcli.proto\x12\x04grpc\"\x13\n" +
	"\x11ListRoutesRequest\"O\n" +
	"\tRouteInfo\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x14\n" +
	"\x05quota\x18\x02 \x01(\tR\x05quota\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\"=\n" +
	"\x12ListRoutesResponse\x12'\n" +
	"\x06routes\x18\x01 \x03(\v2\x0f.grpc.RouteInfoR\x06routes\"\x13\n" +
	"\x11ListQuotasRequest\"{\n" +
	"\tQuotaInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05daily\x18\x02 \x01(\x03R\x05daily\x12\x18\n" +
	"\amonthly\x18\x03 \x01(\x03R\amonthly\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"=\n" +
	"\x12ListQuotasResponse\x12'\n" +
	"\x06quotas\x18\x01 \x03(\v2\x0f.grpc.QuotaInfoR\x06quotas\"\x11\n" +
	"\x0fListKeysRequest\"\x87\x01\n" +
	"\aKeyInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route\x12\x19\n" +
	"\breal_key\x18\x04 \x01(\tR\arealKey\x12!\n" +
	"\finternal_key\x18\x05 \x01(\tR\vinternalKey\"5\n" +
	"\x10ListKeysResponse\x12!\n" +
	"\x04keys\x18\x01 \x03(\v2\r.grpc.KeyInfoR\x04keys\"V\n" +
	"\rAddKeyRequest\x12\x14\n" +
	"\x05route\x18\x01 \x01(\tR\x05route\x12\x19\n" +
	"\breal_key\x18\x02 \x01(\tR\arealKey\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"3\n" +
	"\x0eAddKeyResponse\x12!\n" +
	"\finternal_key\x18\x01 \x01(\tR\vinternalKey\"&\n" +
	"\x10DeleteKeyRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"-\n" +
	"\x11DeleteKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd9\x01\n" +
	"\x0fGetStatsRequest\x12.\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x1a.grpc.GetStatsRequest.ModeR\x04mode\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1b\n" +
	"\tmax_count\x18\x05 \x01(\x05R\bmaxCount\"+\n" +
	"\x04Mode\x12\t\n" +
	"\x05DAILY\x10\x00\x12\v\n" +
	"\aMONTHLY\x10\x01\x12\v\n" +
	"\aVERBOSE\x10\x02\"\x9f\x02\n" +
	"\fDailyStatRow\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"route_path\x18\x02 \x01(\tR\troutePath\x12\x1b\n" +
	"\tlocal_key\x18\x03 \x01(\tR\blocalKey\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x03R\vtotalTokens\x12#\n" +
	"\rlast_activity\x18\b \x01(\tR\flastActivity\"\xfe\x01\n" +
	"\x0eMonthlyStatRow\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"route_path\x18\x02 \x01(\tR\troutePath\x12\x1b\n" +
	"\tlocal_key\x18\x03 \x01(\tR\blocalKey\x12%\n" +
	"\x0etotal_requests\x18\x04 \x01(\x03R\rtotalRequests\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x03R\vtotalTokens\"\x8c\x02\n" +
	"\x0eVerboseStatRow\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x1b\n" +
	"\tlocal_key\x18\x03 \x01(\tR\blocalKey\x12\x1d\n" +
	"\n" +
	"route_path\x18\x04 \x01(\tR\troutePath\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\x03R\fpromptTokens\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x12+\n" +
	"\x11completion_tokens\x18\a \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x03R\vtotalTokens\"\xb7\x01\n" +
	"\x10GetStatsResponse\x121\n" +
	"\n" +
	"daily_rows\x18\x01 \x03(\v2\x12.grpc.DailyStatRowR\tdailyRows\x127\n" +
	"\fmonthly_rows\x18\x02 \x03(\v2\x14.grpc.MonthlyStatRowR\vmonthlyRows\x127\n" +
	"\fverbose_rows\x18\x03 \x03(\v2\x14.grpc.VerboseStatRowR\vverboseRows2\xf9\x02\n" +
	"\fAdminService\x12?\n" +
	"\n" +
	"ListRoutes\x12\x17.grpc.ListRoutesRequest\x1a\x18.grpc.ListRoutesResponse\x12?\n" +
	"\n" +
	"ListQuotas\x12\x17.grpc.ListQuotasRequest\x1a\x18.grpc.ListQuotasResponse\x129\n" +
	"\bListKeys\x12\x15.grpc.ListKeysRequest\x1a\x16.grpc.ListKeysResponse\x123\n" +
	"\x06AddKey\x12\x13.grpc.AddKeyRequest\x1a\x14.grpc.AddKeyResponse\x12<\n" +
	"\tDeleteKey\x12\x16.grpc.DeleteKeyRequest\x1a\x17.grpc.DeleteKeyResponse\x129\n" +
	"\bGetStats\x12\x15.grpc.GetStatsRequest\x1a\x16.grpc.GetStatsResponseB\tZ\a./protob\x06proto3"

var (
	file_grpc_proto_ailocalcli_proto_rawDescOnce sync.Once
	file_grpc_proto_ailocalcli_proto_rawDescData []byte
)

func file_grpc_proto_ailocalcli_proto_rawDescGZIP() []byte {
	file_grpc_proto_ailocalcli_proto_rawDescOnce.Do(func() {
		file_grpc_proto_ailocalcli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_ailocalcli_proto_rawDesc), len(file_grpc_proto_ailocalcli_proto_rawDesc)))
	})
	return file_grpc_proto_ailocalcli_proto_rawDescData
}

var file_grpc_proto_ailocalcli_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_proto_ailocalcli_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_grpc_proto_ailocalcli_proto_goTypes = []any{
	(GetStatsRequest_Mode)(0),  // 0: grpc.GetStatsRequest.Mode
	(*ListRoutesRequest)(nil),  // 1: grpc.ListRoutesRequest
	(*RouteInfo)(nil),          // 2: grpc.RouteInfo
	(*ListRoutesResponse)(nil), // 3: grpc.ListRoutesResponse
	(*ListQuotasRequest)(nil),  // 4: grpc.ListQuotasRequest
	(*QuotaInfo)(nil),          // 5: grpc.QuotaInfo
	(*ListQuotasResponse)(nil), // 6: grpc.ListQuotasResponse
	(*ListKeysRequest)(nil),    // 7: grpc.ListKeysRequest
	(*KeyInfo)(nil),            // 8: grpc.KeyInfo
	(*ListKeysResponse)(nil),   // 9: grpc.ListKeysResponse
	(*AddKeyRequest)(nil),      // 10: grpc.AddKeyRequest
	(*AddKeyResponse)(nil),     // 11: grpc.AddKeyResponse
	(*DeleteKeyRequest)(nil),   // 12: grpc.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),  // 13: grpc.DeleteKeyResponse
	(*GetStatsRequest)(nil),    // 14: grpc.GetStatsRequest
	(*DailyStatRow)(nil),       // 15: grpc.DailyStatRow
	(*MonthlyStatRow)(nil),     // 16: grpc.MonthlyStatRow
	(*VerboseStatRow)(nil),     // 17: grpc.VerboseStatRow
	(*GetStatsResponse)(nil),   // 18: grpc.GetStatsResponse
}
var file_grpc_proto_ailocalcli_proto_depIdxs = []int32{
	2,  // 0: grpc.ListRoutesResponse.routes:type_name -> grpc.RouteInfo
	5,  // 1: grpc.ListQuotasResponse.quotas:type_name -> grpc.QuotaInfo
	8,  // 2: grpc.ListKeysResponse.keys:type_name -> grpc.KeyInfo
	0,  // 3: grpc.GetStatsRequest.mode:type_name -> grpc.GetStatsRequest.Mode
	15, // 4: grpc.GetStatsResponse.daily_rows:type_name -> grpc.DailyStatRow
	16, // 5: grpc.GetStatsResponse.monthly_rows:type_name -> grpc.MonthlyStatRow
	17, // 6: grpc.GetStatsResponse.verbose_rows:type_name -> grpc.VerboseStatRow
	1,  // 7: grpc.AdminService.ListRoutes:input_type -> grpc.ListRoutesRequest
	4,  // 8: grpc.AdminService.ListQuotas:input_type -> grpc.ListQuotasRequest
	7,  // 9: grpc.AdminService.ListKeys:input_type -> grpc.ListKeysRequest
	10, // 10: grpc.AdminService.AddKey:input_type -> grpc.AddKeyRequest
	12, // 11: grpc.AdminService.DeleteKey:input_type -> grpc.DeleteKeyRequest
	14, // 12: grpc.AdminService.GetStats:input_type -> grpc.GetStatsRequest
	3,  // 13: grpc.AdminService.ListRoutes:output_type -> grpc.ListRoutesResponse
	6,  // 14: grpc.AdminService.ListQuotas:output_type -> grpc.ListQuotasResponse
	9,  // 15: grpc.AdminService.ListKeys:output_type -> grpc.ListKeysResponse
	11, // 16: grpc.AdminService.AddKey:output_type -> grpc.AddKeyResponse
	13, // 17: grpc.AdminService.DeleteKey:output_type -> grpc.DeleteKeyResponse
	18, // 18: grpc.AdminService.GetStats:output_type -> grpc.GetStatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_grpc_proto_ailocalcli_proto_init() }
func file_grpc_proto_ailocalcli_proto_init() {
	if File_grpc_proto_ailocalcli_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_ailocalcli_proto_rawDesc), len(file_grpc_proto_ailocalcli_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_ailocalcli_proto_goTypes,
		DependencyIndexes: file_grpc_proto_ailocalcli_proto_depIdxs,
		EnumInfos:         file_grpc_proto_ailocalcli_proto_enumTypes,
		MessageInfos:      file_grpc_proto_ailocalcli_proto_msgTypes,
	}.Build()
	File_grpc_proto_ailocalcli_proto = out.File
	file_grpc_proto_ailocalcli_proto_goTypes = nil
	file_grpc_proto_ailocalcli_proto_depIdxs = nil
}
